### ISSUE TITLE
网络共享中心显示虚拟网卡无网络访问权限。

### ISSUE THREAD

**Issue by NekoNekoNya** [hacking001/v2tap#1]
流量还是直接往物理网卡走，win10 1803。。

**Comment by hacking001** [comment]
这应该是 tun2socks 没有跑起来 ...

**Comment by hacking001** [comment]
你可以启动之后在 CMD 里执行如下命令，结果发一下

**Comment by gggarc** [comment]
===========================================================================
接口列表
  3...80 fa 5b 08 0b 79 ......Realtek PCIe GBE Family Controller
 17...00 ff 7a 0d 8b 8b ......TeamViewer VPN Adapter
 30...02 02 63 3f 3c 67 ......Remote NDIS based Internet Sharing Device
 18...02 00 4c 4f 4f 50 ......Npcap Loopback Adapter
 16...0a 00 27 00 00 10 ......VirtualBox Host-Only Ethernet Adapter
  5...6c 71 d9 df 24 67 ......Realtek RTL8723BE Wireless LAN 802.11n PCI-E NIC
 23...6e 71 d9 df 24 67 ......Microsoft Wi-Fi Direct Virtual Adapter
 14...00 50 56 c0 00 01 ......VMware Virtual Ethernet Adapter for VMnet1
 26...00 50 56 c0 00 08 ......VMware Virtual Ethernet Adapter for VMnet8
 24...00 ff a5 c6 0b 45 ......TAP-Windows Adapter V9
 10...6c 71 d9 df 24 66 ......Bluetooth Device (Personal Area Network)
  1...........................Software Loopback Interface 1
===========================================================================

IPv4 路由表
===========================================================================
活动路由:
网络目标        网络掩码          网关       接口   跃点数
          0.0.0.0          0.0.0.0   192.168.42.129   192.168.42.139     25
        127.0.0.0        255.0.0.0            在链路上         127.0.0.1    331
        127.0.0.1  255.255.255.255            在链路上         127.0.0.1    331
  127.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
      169.254.0.0      255.255.0.0            在链路上   169.254.165.101    281
  169.254.165.101  255.255.255.255            在链路上   169.254.165.101    281
  169.254.255.255  255.255.255.255            在链路上   169.254.165.101    281
     192.168.42.0    255.255.255.0            在链路上    192.168.42.139    281
   192.168.42.139  255.255.255.255            在链路上    192.168.42.139    281
   192.168.42.255  255.255.255.255            在链路上    192.168.42.139    281
     192.168.56.0    255.255.255.0            在链路上      192.168.56.1    281
     192.168.56.1  255.255.255.255            在链路上      192.168.56.1    281
   192.168.56.255  255.255.255.255            在链路上      192.168.56.1    281
     192.168.61.0    255.255.255.0            在链路上      192.168.61.1    291
     192.168.61.1  255.255.255.255            在链路上      192.168.61.1    291
   192.168.61.255  255.255.255.255            在链路上      192.168.61.1    291
    192.168.187.0    255.255.255.0            在链路上     192.168.187.1    291
    192.168.187.1  255.255.255.255            在链路上     192.168.187.1    291
  192.168.187.255  255.255.255.255            在链路上     192.168.187.1    291
        224.0.0.0        240.0.0.0            在链路上         127.0.0.1    331
        224.0.0.0        240.0.0.0            在链路上      192.168.56.1    281
        224.0.0.0        240.0.0.0            在链路上      192.168.61.1    291
        224.0.0.0        240.0.0.0            在链路上     192.168.187.1    291
        224.0.0.0        240.0.0.0            在链路上   169.254.165.101    281
        224.0.0.0        240.0.0.0            在链路上    192.168.42.139    281
  255.255.255.255  255.255.255.255            在链路上         127.0.0.1    331
  255.255.255.255  255.255.255.255            在链路上      192.168.56.1    281
  255.255.255.255  255.255.255.255            在链路上      192.168.61.1    291
  255.255.255.255  255.255.255.255            在链路上     192.168.187.1    291
  255.255.255.255  255.255.255.255            在链路上   169.254.165.101    281
  255.255.255.255  255.255.255.255            在链路上    192.168.42.139    281
===========================================================================
永久路由:
  无

**Comment by hacking001** [comment]
路由表正常，估计是 v2ray 没有正常工作

适配器那里不是显示 `网络电缆被拔出` 的话，就是 v2ray 的问题，反则 tun2socks 没正常启动

**Comment by hacking001** [comment]
启动后打开任务管理器看看后台有没有 `tun2socks.exe` 和 `wv2ray.exe` 两个进程

两个都在的话，那就是 v2ray 没有正常工作了。tun2socks 遇到错误会直接退出的

对了，不知道你 v2ray 配置信息里的地址，是不是填的是域名，换成 IP 看看

**Comment by gggarc** [comment]
tun2socks.exe和wv2ray.exe都有启动，v2ray填IP地址，虚拟网卡也提示无网络访问权限。

**Comment by hacking001** [comment]
那就不好搞了，我没给 tun2socks 和 v2ray 开日志

请等待下一个版本，正在做

**Comment by hacking001** [comment]
请尝试：[1.1.0-BETA](https://github.com/hacking001/v2tap/releases/tag/1.1.0-BETA)

这个版本已加入多配置支持、导入订阅、添加删除编辑等

这是测试版

**Comment by hacking001** [comment]
#3 所以说这个 issue 应该不需要了
