### ISSUE TITLE
选择“绕过局域网”模式时，访问国内网站依然直连，流量未走代理。

### ISSUE THREAD

**Issue by NekoNekoNya** [hacking001/v2tap#3]
![qq 20190124191435](https://user-images.githubusercontent.com/36025713/51674728-7409b380-200c-11e9-95f8-4efa9d1aedca.png)
![qq 20190124191506](https://user-images.githubusercontent.com/36025713/51674750-81bf3900-200c-11e9-88bf-72b37f9e6baf.png)

**Comment by hacking001** [comment]
这是因为啊，这个按钮目前还只是一个摆设

忘记关掉这个按钮了
